BhallaLab/moose-core

README.md
This small pull request is for testing.
=> Fixed the list in readme file. 

basecode/Id.h, basecode/header.h, builtins/Streamer.cpp, builtins/Streamer.h, builtins/StreamerBase.cpp, builtins/StreamerBase.h, builtins/Table.h, builtins/TableBase.cpp, builtins/TableBase.h, shell/Shell.cpp, shell/Shell.h, shell/Wildcard.cpp, tests/python/Rallpacks/rallpacks_cable_hhchannel.py, utility/print_function.hpp
=> Alternative implementation of moose.Streamer 

python/moose/__init__.py
have made changes mainly in python/moose/__init__.py for loacl documentation generation
=> Local Documentation

.travis/travis_prepare_osx.sh, CMakeLists.txt, CheckCXXCompiler.cmake, MooseTests.cmake, cmake_modules/FindGSL.cmake
Documentation on how user can use different compiler with nvidia-cuda compiler. See #200 for details.
=> Fixes to issue #200.

python/moose/SBML/readSBML.py, python/moose/SBML/validation.py, python/moose/SBML/writeSBML.py, python/moose/chemUtil/chemConnectUtil.py, python/moose/genesis/writeKkit.py, python/moose/merge/merge.py
Restoring these files for read and write SBML file, due to bad commit and bad merge
=> Restoring contents after bad commit and bad merge

python/moose/SBML/readSBML.py
…d to moose a errorFlag is set out, rateLaw without unit definition, are taken from the substance units and recalculated for all higher reaction, validator checks if model is valid and send out errormsg if not valid, if model doesn't have atleast one compartment, then errormsg is send out
=> unwanted print statement is removed

python/moose/SBML/readSBML.py
Oct5 : SBML model should at least have one reaction for displaying into GUI
-if in reaction stoichiometry is not defined then assume 1 
-if no base unit defined then assume 1 which is mole
-validator was switched off, which is not correct, so switching ON
=> combined  2 git pulls together

tests/python/test_import.py
Added a test which tests moose module import (incomplete).
=> Fixed moose.merge import.

external/muparser/include/muParserBase.h, external/muparser/include/muParserToken.h, external/muparser/src/muParserTest.cpp, python/rdesigneur/__init__.py, python/rdesigneur/rdesigneur.py, tests/python/abstrModelEqns9.py, tests/python/test_muparser.py, tests/python/test_rdesigneur.py
Similar fixes were applied to chamcham branch #225 .
=> Fixes to rdesigeur import (python2/python3), scaled back chemdt, and auto_ptr to unique_ptr

.travis/travis_build_osx.sh, scripts/Makefile.wheel
Added our personal homebrew formula. This is now maintained by us and not homebrew team. See https://github.com/Homebrew/homebrew-science/pull/6464
- The formula needs to be tested on travis .
=> Test homebrew formula as well on travis.

tests/python/test_negative_value_flag.py
script. This causes test to fail on some unix platform in DEBUG mode.
=> When build in DEBUG mode, we never go to negative values in this test

python/rdesigneur/rdesigneur.py
Fixes earlier changes to Dts for Rdesigneur, which had led to lack of stimulus handling in some electrical models.
=> Added funcDt argument to rdesigneur, with sensible defaults.

python/moose/SBML/readSBML.py
`python3` does not have `has_key`.
=> replace has_key with python3 compatible statement.

diffusion/ConcChanInfo.h, diffusion/Dsolve.cpp, kinetics/ReadKkit.cpp, kinetics/ReadKkit.h, mesh/NeuroNode.cpp, python/rdesigneur/rdesigneur.py
This set of updates are focussed on EndoMesh and ConcChan, affect base code and rdesigneur. Also put in a fix for a problem in NeuroMesh which was reported by valgrind.
=> Rdesigneur and code updates for handling EndoMesh and ConcChan

python/moose/chemUtil/add_Delete_ChemicalSolver.py, python/moose/genesis/writeKkit.py
check to see if model has just CubeMesh/CylMesh if yes set/delete the solver
=> mooseAddChemSolver and mooseDeleteChemSolver is meant for chemical models only

python/rdesigneur/rdesigneur.py, python/rdesigneur/rdesigneurProtos.py, python/rdesigneur/rmoogli.py
Rdesigneur updates for handling arguments, and for display.
=> Rdesigneur updates

python/moose/moose_test.py
Hotfix: Removed writing log to a file. Changes from testing packages. https://github.com/BhallaLab/moose/commit/2253b119ab28eb248b93a9ae409ec69647d1d337
=> HotFix: Update moose_test.py

kinetics/ReadKkit.cpp
reading info field for color and co-ordinates for channel
=> reading info field for channel from kkit file

mesh/EndoMesh.cpp
Fixed bug report #326 
numDimensions
Segvs on showfield.
=> Fixes to EndoMesh

python/moose/SBML/readSBML.py, python/moose/SBML/writeSBML.py, python/moose/chemMerge/merge.py, python/moose/genesis/writeKkit.py
xref pool are not written and cleaned up if part of Reaction/Enzyme or notes, group are checked under all the mesh.
=> xref pool are not wirtten and cleaned up if part of Reaction/Enzyme

python/rdesigneur/rdesigneurProtos.py
In K_AHP, added the line K_AHP.useConcentration = 1
In K_AHP z gate, corrected the value of zB[i] from 1.0 to 1.0+zA[i]
In make_Ca y gate, corrected the value of yA[i] from 0.0 to 5.0 when the potential is less than EREST_ACT
=> Corrected the K_AHP z gate and make_Ca y gate

basecode/header.h, builtins/Streamer.cpp, builtins/Streamer.h, builtins/StreamerBase.cpp, shell/Shell.cpp, tests/python/test_streamer.py, tests/python/test_table_streaming_support.py
=> HOTFIX | Fixes to issue #360. Regression caused by #352 .

builtins/CMakeLists.txt, builtins/Function.cpp, builtins/Function.h, builtins/MooseParser.h, builtins/Variable.cpp, ksolve/FuncTerm.cpp, ksolve/Gsolve.cpp, ksolve/ZombieFunction.cpp, mesh/CylMesh.cpp, pymoose/moosemodule.cpp, python/moose/utils.py, synapse/SeqSynHandler.cpp, tests/python/test_function_controls_reac_rate.py
Various small fixes to make scripts in moose-examples work. Related to https://github.com/BhallaLab/moose-examples/pull/66
=> Examples fixes

python/moose/genesis/writeKkit.py
Combination of #407 and my changes from new python bindings.
=> Merged hrani changes (#407) to mine from from the new bindings

python/moose/SBML/readSBML.py, python/moose/SBML/writeSBML.py
replace getId->id, getId().value,getDataIndex->dataIndex isnstance->isA in writeSBML file
and replace isinstance -> isA in readsbml files
=> replace read and write SBML files with isA instead of isinstance

pymoose/CMakeLists.txt, pymoose/PyRun.cpp, python/setup.cmake.py
These changes fix seg-fault with Python3.9 (see #419).
=> Fixes to Python3.9 build failure 

python/moose/chemUtil/add_Delete_ChemicalSolver.py, python/moose/genesis/writeKkit.py
writeKkit: dangling reaction and enzyme are not saved, 
lsoda is added to solver
=> update to kkitwriter

.github/workflows/pymoose.yml, python/moose/SBML/readSBML.py, python/moose/SBML/writeSBML.py, python/moose/chemMerge/merge.py
Allowed all special character except those not allowed in SBML and Moose
=> revisited special character section in read and write SBML files

.github/workflows/package.yml, .github/workflows/pymoose.yml, AUTHORS, AppleM1Build.md, CHANGELOG.md, INSTALL.md, README.md, UbuntuBuild.md, WindowsBuild.md, builtins/meson.build, diffusion/meson.build, kinetics/meson.build, ksolve/meson.build, meson.build, meson_options.txt, pyproject.toml, python/moose/SBML/readSBML.py, python/moose/neuroml2/reader.py
Puts together workflow for creating packages for Windows, Linux and MacOS using github hosted runners.
It also uploads the generated packages to github release.
=> Modifications for automatic packaging on github
