BhallaLab/moose-core

- Makefile
- pymoose/moosemodule.cpp
NumPy headers location was hardcoded, causing make to fail on OSX
and any other system with non-standard python library location.
This patch adds extraction of the proper path via invocation of
`numpy.get_include()`
Caveat: works for python 2.7 only at the moment
> Fix: locate headers for NumPy

- LICENSE
- README.md
- copyleft
- setup.py
The README already said that moose is licensenced under GPLv3, but
didn't specify "or any later version", like headers in the files.
Clarify that the license is GPLv3+, remove copyleft file which
specified LGPL.
Add the text of the license; various Linux distributions expect this
in packages.
The text is taken from http://www.gnu.org/licenses/gpl.txt.
> Add license text, clarify that GPLv3+ is the license

- builtins/HDF5DataWriter.cpp
- builtins/HDF5DataWriter.h
- builtins/HDF5WriterBase.cpp
- builtins/NSDFWriter.cpp
- builtins/NSDFWriter.h
This allows clean closure of HDF5 files without deleting the corresponding MOOSE objects.
This is necessary for adding more complex data than are handled within MOOSE. One can close the file at the end of MOOSE simulation and then reopen it using h5py or other HDF5 library in the same script and write more data into it.
> Fixed destructor and close in HDF5 writers.

- CMakeLists.txt
More detailed instructions on dependencies in cmake itself.
During build process, messages are emitted about depnedencies and how to install them using apt, yum and brew. Pointers are given to the url from where download and build instructions can be found if packages are not available.
> Added instructions to cmakefile.

- python/setup.py
After d2b857c3a4, python3 setup.py install would not install the
binary extension module because the filename is different.
> Tell setup.py about the .so suffix too

- ksolve/Gsolve.cpp
- ksolve/Gsolve.h
- ksolve/Ksolve.cpp
- ksolve/Ksolve.h
- python/rdesigneur/__init__.py
- python/rdesigneur/rdesigneur.py
- All import statements in python module as python3 style (absolute imports).
- Parallel Ksolve/Gsolve with default 2 threads. Disabled by default. To enable, one has to compile with `-DUSE_CPP11_ASYNC_TO_PARALLELIZE=1`. Support is not added in cmake yet. Still alpha.
> Python3 compatible import and parallel Ksolve/Gsolve

- MooseTests.cmake
- pymoose/melement.cpp
- pymoose/moosemodule.cpp
- pymoose/vec.cpp
- shell/Shell.cpp
- tests/python/test_accessing_existing_paths.py
- tests/python/test_paths.py
- tests/python/test_sbml.py
- tests/python/test_warnigns.py
- utility/print_function.hpp
- When path `/a/b` exists with type `moose.A`, accessing it with `moose.B('/a/b')` is an error.
- When path '/a/b' exists with type `moose.A' , accessing it with `moose.A('/a/b')` ~is a user warning~ is a DeprecationWarning. In future, it will be an error.
> Accessing an existing object

- synapse/SeqSynHandler.cpp
Since the input is an impulse, the amplitude has been normalized by dt. The basal response was already taking care of this, but the sequence response wasn't. It was now been fixed.
> SeqSynHandler fixes - normalized seqActivation by dt

- python/moose/SBML/readSBML.py
- python/moose/SBML/writeSBML.py
- python/moose/genesis/writeKkit.py
readSBML: explicitly ratio is set to 4, so that e2,e1 is balanced, If units are defined in the rate law for the reaction then checks are made and if not in milli mole the base unit then recalculate, spell correction.
writeSBML: instead of printing error msg, saving into string for later use
writekkit : instead of printing error msg, saving into string for later use
> Rate law unit are further cleaned up

- synapse/SeqSynHandler.cpp
retracting seqActivation normalization by dt to restore time-step invariance
> retracting seqActivation normalization by dt to restore time-step invariance

- CMakeLists.txt
- python/setup.cmake.py
Debian related macros are be moved to BhallaLab/moose.
`moose-core` is not python module independant of 'debian' specific install paths.
> Fixes to BhallaLab/moose#224 

- .travis/travis_build_osx.sh
- .travis/travis_prepare_osx.sh
Fixes to travis failure on osx due to missing `pip` command.
> Possible fixes to travis build failure on osx.

- basecode/Id.h
- basecode/header.h
- biophysics/CompartmentBase.cpp
- biophysics/Neuron.cpp
- mesh/NeuroMesh.cpp
- mesh/NeuroNode.cpp
- mesh/NeuroNode.h
- mesh/SpineMesh.cpp
- python/rdesigneur/rdesigneur.py
1. An update/fix: now the ordering of chemical compartments is consistent with the ordering of electrical compartments.
2. Put in a feature so that when CompartmentBase geometry is changed, individual channels can indicate not to rescale their Gbar. This uses a child object named scaleFormula.
Neither of these changes should affect other sections of code, but possibly some of the tutorials and demos on rdesigneur may need checking. Also I'll need to go back and check the demos for my eLife 2017 paper.
> Updates for multiscale modeling

- python/moose/SBML/readSBML.py
- python/moose/SBML/writeSBML.py
Only if valid model exists, then printing the no of compartment,pool,reaction etc
at reaction level a check made to see if path exist while creating a new reaction if exist then id is taken
for Product_formation_, k3 units depends on noofSub , prd was passed which is fixed to sub.
S+E --> SE* (k1) sub
SE* --> S+E (k2) prd
SE* --> E+P (k3) sub
> Few clean up while reading and writing from/to SBML

- ksolve/Stoich.cpp
- ksolve/Stoich.h
- ksolve/VoxelPools.cpp
These commits add a flag to the Stoich object, Stoich::allowNegative,  to allow or prevent negative values for coming up during chemical computations. Default is True, so that negative values are prevented.
> Flag to prevent negative values in chemical computations

- python/rdesigneur/moogul.py
- python/rdesigneur/rdesigneur.py
- python/rdesigneur/rmoogli.py
This introduces a pure matplotlib-based 3D display for neurons as an almost-plugin replacement for moogli. It is slower and less beautiful than moogli, but it is just matplotlib and hence much easier to configure and maintain.
Please check that the tutorials/Rdesigneur examples run with this. They do on my machine.
> New rmoogli and moogul for 3-D morphology display

- python/setup.cmake.py
Install should not require matplotlib. Use can install it later.
> HotFix: Update setup.cmake.py

- python/moose/neuroml2/reader.py
```AttributeError: 'NML2Reader' object has no attribute 'rate_fn_map'```
This is causing failure of moose-examples: https://travis-ci.org/BhallaLab/moose-examples/jobs/436070992
> Hotfix: Neuroml2 fixes.

- CMakeLists.txt
- pymoose/CMakeLists.txt
Changed 'MACOSX' boolean to 'APPLE' . Seems like cmake has deprecated it. Also set the newly introduced policy CMP0045 to FALSE. See the CMakeLists.txt for details and links to wiki page for explanation.
> Hotfix: Fixes to build failure on OSX because cmake does not set MACOSX to 1 anymore

- python/rdesigneur/rdesigneurProtos.py
Fixed so that the classic HH Na and K_DR channels now work properly. The merging of the other prototype channels had led to a conflict between uses and values of the global EREST_ACT parameter.
> Fix to rdesigneurProtos 

- biophysics/Neuron.cpp
- hsolve/HSolveActive.cpp
- hsolve/HSolveActive.h
- hsolve/HSolveActiveSetup.cpp
- hsolve/HSolveInterface.cpp
HSolve fixes: Compute Im correctly by including contributions of external (non-Hsolved) ion channels and receptors
Neuron fixes: When loading channel distributions, ensure that Ca_concs are loaded first, before any ion channels. This ensures that ion channels with dependencies on Ca_conc have something to connect to when they are built.
> Fixes to Hsolve and Neuron

- builtins/SocketStreamer.cpp
(manylinux1) which is used to build python wheel. This manylinux1 is
ported to cento6, keep is option.
> HOTFIX! SO_REUSEPORT is not always defined. The build fails on centos-5

- .travis/travis_build_linux.sh
- .travis/travis_build_osx.sh
Not sure how travis is configured for sockets. Sometimes the tests passes and sometimes it waits infinitely for the sokcet. Disabling a socket test on OSX+Travis. The streamer was meant for Linux servers only. The test passes on local OSX machine.
> Travis Fix | Don't run streamer multitab tests on OSX/Travis.

- python/moose/neuroml/MorphML.py
This works, but only because of an implementation detail: short
strings are interned as part of module code. But the rules are complicated
and we should not rely on this.
See http://guilload.com/python-string-interning/ for a nice writeup.
Python3.8 now warns about this.
> neuroml: do not use "is" with strings

- python/moose/SBML/writeSBML.py
- python/moose/genesis/writeKkit.py
comapartment as group in genesis
> while writting genesis file compartment is added as a group

- basecode/Id.cpp
- basecode/global.cpp
- basecode/global.h
- builtins/Streamer.cpp
- builtins/Streamer.h
- builtins/StreamerBase.cpp
- builtins/StreamerBase.h
- builtins/Table.cpp
- builtins/Table.h
- pymoose/CMakeLists.txt
- python/moose/neuroml2/reader.py
- scheduling/Clock.cpp
- shell/Neutral.cpp
- shell/Wildcard.cpp
- tests/py_moose/test_streamer.py
- tests/py_moose/test_table_streaming_support.py
- utility/CMakeLists.txt
- utility/cnpy.cpp
- utility/cnpy.hpp
- utility/test_cnpy.cpp
Followup on #360 and #362 
- `moose.Streamer` now support `npy` format (version 2.0)
- Fixes a minor bug in `neuroml2` reader (related to python3 only).
> Bugfix | moose.Streamer streams to numpy format correctly

- biophysics/CompartmentBase.h
- kinetics/Pool.cpp
- pymoose/CMakeLists.txt
- pymoose/PyRun.cpp
- pymoose/melement.cpp
- pymoose/moosemodule.cpp
- pymoose/moosemodule.h
- pymoose/pymooseinit.cpp
- pymoose/vec.cpp
- python/moose/server.py
- shell/Neutral.h
- Fixes #397 (details https://github.com/BhallaLab/moose-core/issues/397#issuecomment-602012864 )
- Minor refactoring and cleanup.
Caused by translating `const char*` to unicode bytes in python module (caused by one of my PR). On debian, this bug did not show up because it was converted to `const char*` properly by python api. On centos-7, due to old compiler or bad locale settings, this did not happen.
To make matter worse, when pymoose is compiled with the same GCC with which python is compiled on centos, this bug does not appear. Another workaround would be to set locale settings inside the c++ extension.
In the end, it was a matter of changing `s*` (unicode) to `s` in the Parse_TupleArgs function.
Diagnostics are on github issue.
> HOTFIX | Fix to https://github.com/BhallaLab/moose-core/issues/397

- ksolve/Stoich.cpp
- pybind11/helper.cpp
- pybind11/pymoose.cpp
- python/moose/__init__.py
- tests/core/test_api.py
- Fixes typo #426 
- `getFieldNames` also available on the moose element. For example:
```python
>>> a = moose.Stoich('a')
>>> moose.getFieldNames(a)    # available before
>>> a.getFieldNames()               # added in this PR
```
> Typo and partial fixes to Issue 426

- pybind11/helper.h
- python/moose/__init__.py
This fixes #429. If a user try to delete a non-existent path, moose raises a `ValueError` exception.
> Fixes to #429

- python/moose/__init__.py
`moose.__version__` was mapped to a function call. Now `moose.__version__` returns the output of `moose.version()` rather than a function object.
> __version__ was mapped to a lambda

- basecode/Eref.cpp
- basecode/Eref.h
- basecode/ObjId.h
- biophysics/CompartmentBase.cpp
- biophysics/CompartmentBase.h
- builtins/CMakeLists.txt
- builtins/InputVariable.cpp
- builtins/InputVariable.h
- builtins/NSDFWriter.cpp
- builtins/NSDFWriter.h
- builtins/NSDFWriter2.cpp
- builtins/NSDFWriter2.h
- kinetics/ReadKkit.cpp
- kinetics/ReadKkit.h
- ksolve/Gsolve.cpp
- python/rdesigneur/moogul.py
- python/rdesigneur/nsdfview.py
- python/rdesigneur/rdesigneur.py
- python/rdesigneur/rmoogli.py
- scheduling/Clock.cpp
Merging zombie gone branch to master branch
> Zombie gone

- CMakeLists.txt
- CheckCXXCompiler.cmake
In CMake NSDF is set  if hdf5 library found and min default gcc required is 5.*
> Patch min gcc5 hdf5default

- CMakeLists.txt
- CheckCXXCompiler.cmake
- python/moose/SBML/readSBML.py
- python/moose/SBML/writeSBML.py
Edge cases for with the model 
- NN_mapk15.g which has extra Neutral path before compartment is taken care while writing and reading into SBML
- OSC_different_vols 
-- where pool being a parent and product, Stoichiometry need to reduce while reading the model
-- function expression fixed if multiple of same pool exist
These changes made rdesignuer examples to work with SBML files and gives out the same result when passed genesis file
Corrected cmake version to 3.1 which was checked for 4.9
> Cleanup sbml

- .github/workflows/pymoose.yml
- python/moose/utils.py
- setup.py
merge py3.10update to jalebi branch
> Py3.10update

- diffusion/Dsolve.cpp
- diffusion/Dsolve.h
- kinetics/Reac.cpp
- ksolve/FuncRateTerm.h
- ksolve/Gsolve.cpp
- ksolve/Gsolve.h
- ksolve/Ksolve.cpp
- ksolve/Ksolve.h
- ksolve/KsolveBase.h
- ksolve/Stoich.cpp
- ksolve/Stoich.h
- ksolve/VoxelPoolsBase.cpp
- ksolve/VoxelPoolsBase.h
Used in the rare cases where reac rates differe between voxels, such as when the reacs are controlled by a function.
> Field in Ksolve to view forward rates across voxels

- .github/workflows/pymoose.yml
- CMakeLists.txt
- INSTALL.md
- pybind11/Finfo.cpp
- pybind11/MooseVec.cpp
- pybind11/MooseVec.h
- pybind11/helper.cpp
- pybind11/pymoose.cpp
- setup.py
- Updated pybind11 includes in source code 
- Fixed cmake file for finding system pybind11
- Updated github workflow to use micromamba setup from github marketplace
> Fix for pybind11 and updates in github actions

- python/rdesigneur/rdesigneur.py
Without the line, the funcName does not show up in the module's namespace and the funcName function cannot be executed in the next line.
> Execute the module to access the funtion in its namespace
